# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blue/CLionProjects/QtProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blue/CLionProjects/QtProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/CLionProjects/QtProject/CMakeFiles /home/blue/CLionProjects/QtProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blue/CLionProjects/QtProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QtProject

# Build rule for target.
QtProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtProject
.PHONY : QtProject

# fast build rule for target.
QtProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/build
.PHONY : QtProject/fast

#=============================================================================
# Target rules for targets named QtProject_autogen

# Build rule for target.
QtProject_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtProject_autogen
.PHONY : QtProject_autogen

# fast build rule for target.
QtProject_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject_autogen.dir/build.make CMakeFiles/QtProject_autogen.dir/build
.PHONY : QtProject_autogen/fast

Controller/SlotController.o: Controller/SlotController.cpp.o
.PHONY : Controller/SlotController.o

# target to build an object file
Controller/SlotController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Controller/SlotController.cpp.o
.PHONY : Controller/SlotController.cpp.o

Controller/SlotController.i: Controller/SlotController.cpp.i
.PHONY : Controller/SlotController.i

# target to preprocess a source file
Controller/SlotController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Controller/SlotController.cpp.i
.PHONY : Controller/SlotController.cpp.i

Controller/SlotController.s: Controller/SlotController.cpp.s
.PHONY : Controller/SlotController.s

# target to generate assembly for a file
Controller/SlotController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Controller/SlotController.cpp.s
.PHONY : Controller/SlotController.cpp.s

Model/SlotModel.o: Model/SlotModel.cpp.o
.PHONY : Model/SlotModel.o

# target to build an object file
Model/SlotModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Model/SlotModel.cpp.o
.PHONY : Model/SlotModel.cpp.o

Model/SlotModel.i: Model/SlotModel.cpp.i
.PHONY : Model/SlotModel.i

# target to preprocess a source file
Model/SlotModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Model/SlotModel.cpp.i
.PHONY : Model/SlotModel.cpp.i

Model/SlotModel.s: Model/SlotModel.cpp.s
.PHONY : Model/SlotModel.s

# target to generate assembly for a file
Model/SlotModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/Model/SlotModel.cpp.s
.PHONY : Model/SlotModel.cpp.s

QtProject_autogen/mocs_compilation.o: QtProject_autogen/mocs_compilation.cpp.o
.PHONY : QtProject_autogen/mocs_compilation.o

# target to build an object file
QtProject_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/QtProject_autogen/mocs_compilation.cpp.o
.PHONY : QtProject_autogen/mocs_compilation.cpp.o

QtProject_autogen/mocs_compilation.i: QtProject_autogen/mocs_compilation.cpp.i
.PHONY : QtProject_autogen/mocs_compilation.i

# target to preprocess a source file
QtProject_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/QtProject_autogen/mocs_compilation.cpp.i
.PHONY : QtProject_autogen/mocs_compilation.cpp.i

QtProject_autogen/mocs_compilation.s: QtProject_autogen/mocs_compilation.cpp.s
.PHONY : QtProject_autogen/mocs_compilation.s

# target to generate assembly for a file
QtProject_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/QtProject_autogen/mocs_compilation.cpp.s
.PHONY : QtProject_autogen/mocs_compilation.cpp.s

View/MainWindow.o: View/MainWindow.cpp.o
.PHONY : View/MainWindow.o

# target to build an object file
View/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MainWindow.cpp.o
.PHONY : View/MainWindow.cpp.o

View/MainWindow.i: View/MainWindow.cpp.i
.PHONY : View/MainWindow.i

# target to preprocess a source file
View/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MainWindow.cpp.i
.PHONY : View/MainWindow.cpp.i

View/MainWindow.s: View/MainWindow.cpp.s
.PHONY : View/MainWindow.s

# target to generate assembly for a file
View/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MainWindow.cpp.s
.PHONY : View/MainWindow.cpp.s

View/MyGraphicsView.o: View/MyGraphicsView.cpp.o
.PHONY : View/MyGraphicsView.o

# target to build an object file
View/MyGraphicsView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MyGraphicsView.cpp.o
.PHONY : View/MyGraphicsView.cpp.o

View/MyGraphicsView.i: View/MyGraphicsView.cpp.i
.PHONY : View/MyGraphicsView.i

# target to preprocess a source file
View/MyGraphicsView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MyGraphicsView.cpp.i
.PHONY : View/MyGraphicsView.cpp.i

View/MyGraphicsView.s: View/MyGraphicsView.cpp.s
.PHONY : View/MyGraphicsView.s

# target to generate assembly for a file
View/MyGraphicsView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/MyGraphicsView.cpp.s
.PHONY : View/MyGraphicsView.cpp.s

View/StartWindow.o: View/StartWindow.cpp.o
.PHONY : View/StartWindow.o

# target to build an object file
View/StartWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/StartWindow.cpp.o
.PHONY : View/StartWindow.cpp.o

View/StartWindow.i: View/StartWindow.cpp.i
.PHONY : View/StartWindow.i

# target to preprocess a source file
View/StartWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/StartWindow.cpp.i
.PHONY : View/StartWindow.cpp.i

View/StartWindow.s: View/StartWindow.cpp.s
.PHONY : View/StartWindow.s

# target to generate assembly for a file
View/StartWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/View/StartWindow.cpp.s
.PHONY : View/StartWindow.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... QtProject_autogen"
	@echo "... QtProject"
	@echo "... Controller/SlotController.o"
	@echo "... Controller/SlotController.i"
	@echo "... Controller/SlotController.s"
	@echo "... Model/SlotModel.o"
	@echo "... Model/SlotModel.i"
	@echo "... Model/SlotModel.s"
	@echo "... QtProject_autogen/mocs_compilation.o"
	@echo "... QtProject_autogen/mocs_compilation.i"
	@echo "... QtProject_autogen/mocs_compilation.s"
	@echo "... View/MainWindow.o"
	@echo "... View/MainWindow.i"
	@echo "... View/MainWindow.s"
	@echo "... View/MyGraphicsView.o"
	@echo "... View/MyGraphicsView.i"
	@echo "... View/MyGraphicsView.s"
	@echo "... View/StartWindow.o"
	@echo "... View/StartWindow.i"
	@echo "... View/StartWindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

